#!/usr/bin/env bash
set -e

echo "=== 1. システムパッケージの更新とインストール ==="
sudo apt update
sudo apt install -y \
  git \
  curl \
  zsh \
  tmux \
  ripgrep \
  fd-find \
  stow \
  tree \
  bat \
  zoxide \
  build-essential

echo "=== 2. 個別ツールの追加・最新版セットアップ ==="
mkdir -p ~/.local/bin

# PATHの追加確認
if ! echo "$PATH" | grep -q "$HOME/.local/bin"; then
  echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.profile
fi

# fd-find のエイリアス作成 (fdfind -> fd)
if [ ! -f ~/.local/bin/fd ] && command -v fdfind &> /dev/null; then
  ln -s $(which fdfind) ~/.local/bin/fd
fi

# bat のエイリアス作成 (batcat -> bat)
if [ ! -f ~/.local/bin/bat ] && command -v batcat &> /dev/null; then
  ln -s $(which batcat) ~/.local/bin/bat
fi

# micro (最新版バイナリを取得)
echo "Installing latest micro..."
cd ~/.local/bin
curl https://getmic.ro | bash
cd "$HOME"

# fzf (公式リポジトリから最新版を取得・ビルド)
if [ ! -d "$HOME/.fzf" ]; then
  echo "Installing latest fzf..."
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install --all --no-bash --no-fish
else
  echo "Updating fzf..."
  cd ~/.fzf && git pull && ./install --all --no-bash --no-fish
  cd "$HOME"
fi

echo "=== 3. dotfiles ディレクトリと初期設定ファイルの生成 ==="
DOTFILES_DIR="$HOME/dotfiles"
mkdir -p "$DOTFILES_DIR"/{zsh,tmux,fzf,ripgrep,fd,zoxide,tree,stow,micro,bat}

# zsh 設定テンプレート (未存在時のみ作成)
if [ ! -f "$DOTFILES_DIR/zsh/.zshrc" ]; then
  cat << 'CONFIG' > "$DOTFILES_DIR/zsh/.zshrc"
# ~/.zshrc generated by dotfiles setup

# PATH
export PATH="$HOME/.local/bin:$PATH"

# Default Editor
export EDITOR="micro"

# zoxide init
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init zsh)"
fi

# fzf keybindings & completion (latest fzf load)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Aliases
alias ls='ls --color=auto'
alias ll='ls -la'
alias cat='bat'
CONFIG
fi

# tmux 設定テンプレート (未存在時のみ作成)
if [ ! -f "$DOTFILES_DIR/tmux/.tmux.conf" ]; then
  cat << 'CONFIG' > "$DOTFILES_DIR/tmux/.tmux.conf"
# ~/.tmux.conf generated by dotfiles setup
set -g mouse on
set -g default-terminal "screen-256color"
CONFIG
fi

# micro 設定ディレクトリ構造の準備
mkdir -p "$DOTFILES_DIR/micro/.config/micro"

echo "=== 4. GNU Stow によるシンボリックリンクの適用 ==="
cd "$DOTFILES_DIR"

# 既存の ~/.zshrc や ~/.tmux.conf がある場合のバックアップ処理
[ -f "$HOME/.zshrc" ] && [ ! -L "$HOME/.zshrc" ] && mv "$HOME/.zshrc" "$HOME/.zshrc.bak"
[ -f "$HOME/.tmux.conf" ] && [ ! -L "$HOME/.tmux.conf" ] && mv "$HOME/.tmux.conf" "$HOME/.tmux.conf.bak"

# stow 実行
for pkg in zsh tmux fzf ripgrep fd zoxide tree stow micro bat; do
  stow "$pkg"
done

echo "=== セットアップ完了 ==="
echo "主要ツールのバージョン確認:"
echo "- micro:  $(~/.local/bin/micro -version 2>/dev/null || echo 'Not found')"
echo "- fzf:    $(~/.fzf/bin/fzf --version 2>/dev/null || echo 'Not found')"
echo "- zoxide: $(zoxide --version 2>/dev/null || echo 'Not found')"
echo ""
echo "デフォルトシェルを zsh に変更する場合は以下を実行してください:"
echo "  chsh -s \$(which zsh)"
